### ISSUE TITLE
Just add some more features(voice commands) to it

### ISSUE THREAD

**Issue by Kamalpreet-3223** [Kamalpreet-3223/Kamalexa#1]
I have added basic voice commands.

If you can add more commands and they are usefull and interesting then go for it.

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this?

**Comment by Kamalpreet-3223** [comment]
Anyone can work on this. No need for assigning
Just do code and raise a PR 
I will accept it !!

**Comment by para-docx** [comment]
@Kamalpreet-3223  hii i just made a pr pls see to this, hopefully my contribution is meaningful

**Comment by Kamalpreet-3223** [comment]
Your contribution was great @para-docx
